"""Materialize the deterministic AEL-CEP Stage-0 golden package.

Stage 0 is deliberately a no-effect synthetic operating-characteristic
fixture.  This tool is the one reproducible writer for the package under
``studies/ael-cep/stage-0``: it derives every generated byte from the frozen
protocol seed, then either atomically writes the package or checks for exact
byte drift without changing any existing file.
"""

from __future__ import annotations

import argparse
import hashlib
from collections.abc import Sequence
from pathlib import Path
from typing import Any

from ael import coevolution as core
from ael.coevolution_bundle import (
    AdapterError,
    check_bundle,
    load_bundle,
    load_protocol,
    materialize_bundle,
    render_bundle_report,
    write_json_atomic,
    write_text_atomic,
)
from ael.coevolution_simulator import (
    SIMULATION_CLOCK_VERSION,
    SIMULATOR_SCHEMA_VERSION,
    WORLD_MODEL_VERSION,
    default_protocol,
    simulate,
)

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "studies" / "ael-cep" / "stage-0"
STAGE0_SEED = 20260815


def _paths(output: Path) -> dict[str, Path]:
    return {
        "protocol": output / "protocol.json",
        "bundle": output / "trajectory-bundle.json",
        "report": output / "report.md",
        "readme": output / "README.md",
    }


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _render_readme(protocol: dict[str, Any], bundle: dict[str, Any], report: str) -> str:
    """Return the deterministic package-level README.

    The report digest is intentionally included so a report-only edit is
    visible in the package summary and in ``--check`` mode.
    """

    protocol_hash = core.protocol_hash(protocol)
    report_hash = hashlib.sha256(report.encode("utf-8")).hexdigest()
    return "\n".join(
        [
            "# AEL-CEP Stage 0 golden package",
            "",
            "This directory is a deterministic, synthetic no-effect fixture for",
            "the AEL Coevolution Protocol (AEL-CEP). It is generated by",
            "`tools/materialize_ael_cep_stage0.py` and is safe to regenerate",
            "locally without model calls, live tools, external effects, or",
            "network access.",
            "",
            "## Frozen identity",
            "",
            f"- Protocol: `{protocol['protocol_id']}`",
            f"- Epoch: `{protocol['epoch']['epoch_id']}`",
            f"- Seed: `{protocol['simulation']['seed']}`",
            f"- Protocol hash: `{protocol_hash}`",
            f"- Bundle: `{bundle['bundle_id']}`",
            f"- Bundle hash: `{bundle['bundle_hash']}`",
            f"- Records: {len(bundle['records'])}",
            f"- Report SHA-256: `{report_hash}`",
            "",
            "## Files",
            "",
            "- `protocol.json` — frozen Stage-0 protocol and matched budgets.",
            "- `trajectory-bundle.json` — hash-linked synthetic ledger and projections.",
            "- `report.md` — descriptive projection derived from the validated ledger.",
            "- `README.md` — this deterministic package boundary and identity summary.",
            "",
            "## Regenerate and check",
            "",
            "```shell",
            "uv run python tools/materialize_ael_cep_stage0.py",
            "uv run python tools/materialize_ael_cep_stage0.py --check",
            "```",
            "",
            "The `--check` form fails closed on missing files or any byte drift; it",
            "never rewrites the package.",
            "",
            "## Claim boundary",
            "",
            f"- Simulator schema: `{SIMULATOR_SCHEMA_VERSION}`",
            f"- Synthetic world model: `{WORLD_MODEL_VERSION}`",
            f"- Simulated clock: `{SIMULATION_CLOCK_VERSION}`",
            "- This is operating-characteristic and contract evidence only.",
            "- It is not evidence of real-agent capability, evaluator validity,",
            "  superiority, safety, production readiness, or external outcomes.",
            "- The bundle intentionally forbids live effects and contains no real",
            "  model, customer, task-secret, credential, or tool-execution payload.",
            "",
        ]
    )


def materialize(output: Path, *, check: bool = False) -> dict[str, Any]:
    """Materialize or byte-check the complete Stage-0 package."""

    target = output if output.is_absolute() else ROOT / output
    paths = _paths(target)
    protocol = default_protocol(seed=STAGE0_SEED)
    protocol_result = write_json_atomic(paths["protocol"], protocol, check=check)

    # Always load from the canonical protocol file after the protocol write or
    # check. This proves that the bundle and report are derived from the exact
    # bytes under review, rather than an unmaterialized in-memory convenience.
    frozen, protocol_raw_sha256 = load_protocol(paths["protocol"])
    bundle = simulate(frozen)
    bundle_result = materialize_bundle(paths["protocol"], paths["bundle"], bundle, check=check)
    validated_bundle = load_bundle(paths["bundle"], protocol=frozen)
    projection = check_bundle(paths["protocol"], paths["bundle"])
    report = render_bundle_report(frozen, validated_bundle, projection)
    report_result = write_text_atomic(paths["report"], report, check=check)
    readme = _render_readme(frozen, validated_bundle, report)
    readme_result = write_text_atomic(paths["readme"], readme, check=check)

    return {
        "status": "checked" if check else "materialized",
        "output": str(target),
        "protocol_id": frozen["protocol_id"],
        "protocol_hash": core.protocol_hash(frozen),
        "protocol_raw_sha256": protocol_raw_sha256,
        "bundle_id": validated_bundle["bundle_id"],
        "bundle_hash": validated_bundle["bundle_hash"],
        "record_count": len(validated_bundle["records"]),
        "files": {
            "protocol": protocol_result,
            "bundle": bundle_result,
            "report": report_result,
            "readme": readme_result,
        },
    }


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        "--output-dir",
        dest="output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="package directory (default: studies/ael-cep/stage-0)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="check exact generated bytes without creating or rewriting files",
    )
    args = parser.parse_args(argv)
    try:
        result = materialize(args.output, check=args.check)
    except (AdapterError, core.CoevolutionError, OSError, ValueError) as exc:
        parser.exit(2, f"ael-cep stage0 materializer failed: {exc}\n")
    print(
        f"AEL-CEP Stage 0 {result['status']}: "
        f"{result['record_count']} records; bundle={result['bundle_hash']}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
